### ISSUE TITLE
十位数的UID不能查询

### ISSUE THREAD

**Issue by Koukotsukan** [czp3009/crc32-crack#2]
测试弹幕ID: 725be011, cf6bca56

**Comment by czp3009** [comment]
目前所用的 crc32 快速反查算法是从 https://github.com/zacyu/bilibili-helper/blob/master/src/js/libs/crc32.js 抄来的, 不支持超过 int(非 unsigned int) 的原文, 详见 readme 第一行.

**Comment by Koukotsukan** [comment]
明白，谢谢大佬
